server:
    port: 5600
spring:
    application:
        name: api-tests
    cloud:
        config:
            username: ${CONFIG_USERNAME}
            password: ${CONFIG_PASSWORD}
    config:
        import: optional:configserver:http://www.turbolessons.com:9999/