server:
  port: 5001
spring:
  application:
    name: event-service
  config:
    import: optional:configserver:http://config-service:9999/
  cloud:
    config:
      enabled: true
      fail-fast: false
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}

# OpenAPI Documentation Configuration
springdoc:
  api-docs:
    path: /api/lessons/v3/api-docs
  swagger-ui:
    path: /api/lessons/swagger-ui.html
    operationsSorter: method
  packages-to-scan: com.turbolessons.eventservice.controller