server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
  config:
    import: optional:configserver:http://config-service:9999/
