networks:
  turbolessons_cloud_service_net:
  email-service_net:
  event-service_net:
  message-service_net:
services:

  service-registry:
    image: noslenj/service-registry:test
    container_name: service-registry
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    ports:
      - "8761:8761"
    networks:
      - turbolessons_cloud_service_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  admin-service:
    image: noslenj/admin-service:test
    container_name: admin-service
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    ports:
      - "5002:5002"
    networks:
      - turbolessons_cloud_service_net

  email-service:
    image: noslenj/email-service:test
    container_name: email-service
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    ports:
      - "5003:5003"
    networks:
      - turbolessons_cloud_service_net
      - email-service_net

  message-service:
    image: noslenj/message-service:test
    container_name: message-service
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    ports:
      - "5005:5005"
    networks:
      - turbolessons_cloud_service_net
      - message-service_net

  event-service:
    image: noslenj/event-service:test
    container_name: event-service
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    ports:
      - "5001:5001"
    networks:
      - turbolessons_cloud_service_net
      - event-service_net
    depends_on:
      lessondb:
        condition: service_healthy

  payment-service:
    image: noslenj/payment-service:test
    container_name: payment-service
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    ports:
      - "5010:5010"
    networks:
      - turbolessons_cloud_service_net

  video-service:
    image: noslenj/video-service:test
    container_name: video-service
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root-test.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    volumes:
      - /Users/noslen/DevProjects/google-cloud:/gcs
    ports:
      - "5004:5004"
    networks:
      - turbolessons_cloud_service_net

  api-gateway:
    image: noslenj/api-gateway:test
    container_name: api-gateway
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    environment:
      SPRING_PROFILES_ACTIVE: integration
    ports:
      - "8080:8080"
    networks:
      - turbolessons_cloud_service_net

  lessondb:
    image: noslenj/lessondb:test
    container_name: lessondb
    env_file:
      - ./root.env
    ports:
      - "5051:3306"
    networks:
      - turbolessons_cloud_service_net
      - event-service_net
    volumes:
      - lessondb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  emaildb:
    image: mongo:latest
    container_name: emaildb
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    ports:
      - "5053:27017"
    networks:
      - turbolessons_cloud_service_net
      - email-service_net

  messagedb:
    image: mongo:latest
    container_name: messagedb
    restart: always
    env_file:
      - /Users/noslen/DevProjects/turbolessons_scripts/root.env
    ports:
      - "5055:27017"
    networks:
      - turbolessons_cloud_service_net
      - message-service_net


volumes:
  lessondb_data: