name: event-service-test

on:
  push:
    paths:
      - "turbolessons/event-service/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Checkout code
      uses: actions/checkout@v3.6.0
      
    - name: Run Maven Tests
      working-directory: turbolessons/event-service
      run: |
        mvn test -DOKTA_CLIENT_ID=${{ secrets.OKTA_CLIENT_ID }} \
        -DOKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }} \
        -DOKTA_ISSUER=${{ secrets.OKTA_ISSUER }} \

