name: payment-service-docker

on:
  push:
    branches:
      - 'master'
    paths:
      - 'turbolessons/payment-service/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Run Maven Tests
        working-directory: turbolessons/payment-service
        run: |
          mvn test -DOKTA_API_SERVICES_ID=${{ secrets.OKTA_API_SERVICES_ID }} \
          -DOKTA_API_SERVICES_SECRET=${{ secrets.OKTA_API_SERVICES_SECRET }} \
          -DOKTA_ISSUER=${{ secrets.OKTA_ISSUER }} \
          -DOKTA_CLIENT_ID=${{ secrets.OKTA_CLIENT_ID }} \
          -DOKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }} \
          -DSTRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }} \
          -DSTRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push payment-service
        uses: docker/build-push-action@v4
        with:
          context: turbolessons/payment-service
          push: true
          tags: noslenj/payment-service:latest
      
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: "https://mostly-certain-primate.ngrok-free.app/"
          user: "noslen"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "payment_service"
      
