server:
  port: 5002
spring:
  application:
    name: admin-service
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
    config:
      enabled: false
      fail-fast: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/


spring.autoconfigure.exclude:
  - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration