server:
  port: 5002
spring:
  application:
    name: admin-service
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
    config:
      enabled: false
      fail-fast: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-secret: ${OKTA_CLIENT_SECRET}
    client-id: ${OKTA_CLIENT_ID}
  client:
    token: ${ADMIN_SERVICE_API_TOKEN}
    orgUrl: ${OKTA_ORG_URL}


spring.autoconfigure.exclude:
  - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration